// <auto-generated/>
using System.Reflection;
using System.Runtime.CompilerServices;

[assembly: InternalsVisibleToAttribute("Paket.VisualStudio.Tests")]
[assembly: AssemblyTitleAttribute("Paket.VisualStudio")]
[assembly: AssemblyProductAttribute("Paket.VisualStudio")]
[assembly: AssemblyDescriptionAttribute("Manage your Paket dependencies from Visual Studio!")]
[assembly: AssemblyVersionAttribute("0.15.7")]
[assembly: AssemblyFileVersionAttribute("0.15.7")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.15.7";
    }
}
