// <auto-generated/>
using System.Reflection;
using System.Runtime.CompilerServices;

[assembly: InternalsVisibleToAttribute("Paket.VisualStudio.Tests")]
[assembly: AssemblyTitleAttribute("Paket.VisualStudio")]
[assembly: AssemblyProductAttribute("Paket.VisualStudio")]
[assembly: AssemblyDescriptionAttribute("Manage your Paket dependencies from Visual Studio!")]
[assembly: AssemblyVersionAttribute("0.37.8")]
[assembly: AssemblyFileVersionAttribute("0.37.8")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String InternalsVisibleTo = "Paket.VisualStudio.Tests";
        internal const System.String AssemblyTitle = "Paket.VisualStudio";
        internal const System.String AssemblyProduct = "Paket.VisualStudio";
        internal const System.String AssemblyDescription = "Manage your Paket dependencies from Visual Studio!";
        internal const System.String AssemblyVersion = "0.37.8";
        internal const System.String AssemblyFileVersion = "0.37.8";
    }
}
